# Test job for GitHub authentication
test-github-auth:
  stage: test
  tags:
    - shell
  variables:
    GIT_STRATEGY: clone
  script:
    - echo "Testing GitHub authentication..."
    - python3 scripts/test_github_auth.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual