# Test job for GitHub authentication
test-github-auth:
  stage: test
  tags:
    - shell
  variables:
    GIT_STRATEGY: clone
  script:
    - echo "Testing GitHub authentication..."
    - python3 scripts/test_github_auth.py
  allow_failure: false
  rules:
    - if: '$CI_PIPELINE_SOURCE'
      when: always
    - when: always